### ISSUE TITLE
update guides to use compose v2 syntax

### ISSUE THREAD

**Issue by rade** [weaveworks/guides#178]
Everybody is being told to use the compose v2 syntax. Performing a naive translation of v1 (as found in our guides) to v2 does not yield a working system using weave. Many users trip over that.

AFAICT, the magic stanza that makes everything work as before is adding `network_mode: "bridge"` to all service definitions, e.g.

```
version: '2'

services:
 nginx:
    image: nginx
    container_name: nginx
    network_mode: "bridge"
```

and then use the Weave Docker API Proxy as before.

**I suggest we do this asap**.

Beyond that, there is the option of using the Weave Docker Network plugin, via,

```
networks:
  default:
    driver: weavemesh
```

but getting containers to use weaveDNS that way seems a bit of a faff. We need to work out whether there is a sane way to do it.

Finally, one may want to configure multiple networks, and place containers on them. compose v2 allows that, so some examples of doing that with weave networking would be good.

Overall, we need to provide users with some guidance here on what route to choose based on what they are trying to do.

One final request: Can we please, please, publish a guide or blog post with the minimal weave+compose setup. AFAICT it requires just 6 steps:
1. download weave + chmod
2. download compose + chmod
3. create `docker-compose.yml` file like the one above
4. `weave launch`
5. `eval $(weave env)`
6. `docker-compose up -d`

**Comment by pidster** [comment]
Further confirmation required, but 

```
services
  ubuntu:
    image: ubuntu
    hostname: ubuntu
    domainname: weave.local.
    dns_search: weave.local.
    network_mode: weave
    dns: 172.17.0.1
```

[edit]

The reverse DNS lookup works correctly if the IP is on another host, but fails if the IP/container is on the same host as source of the request.
